name: mypy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 2  # To retrieve the preceding commit for changed files step

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            '**.py'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install mypy
          
      - name: mypy
        continue-on-error: true
        run: |
          mypy ${{ steps.changed-files.outputs.all_changed_files }} --strict --ignore-missing-imports --pretty
