name: mypy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 2  # To retrieve the preceding commit for changed files step

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            **.py
            **/*.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: |
          pip install mypy
          
      - name: mypy
        id: mypy
        continue-on-error: true
        run: |
          mypy ${{ steps.changed-files.outputs.all_changed_files }} --strict --ignore-missing-imports --pretty 2>&1 | tee mypy_output.log
          REPORT="$(cat mypy_output.log)"
          REPORT="${REPORT//'%'/'%25'}"
          REPORT="${REPORT//$'\n'/'%0A'}"
          REPORT="${REPORT//$'\r'/'%0D'}"
          echo "::set-output name=REPORT::$REPORT"
          echo "::set-output name=SUMMARY::$(tail -n 1 mypy_output.log)"
          
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: mypy

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            mypy:
            <details>
              <summary>
                ${{ steps.mypy.outputs.SUMMARY }}
              </summary>
              <pre><code>${{ steps.mypy.outputs.REPORT }}</code></pre>
            </details>
          edit-mode: replace
